drop DATABASE InventoryManagerDb;
CREATE TABLE Corps
(
	ID INT PRIMARY KEY IDENTITY,
	[Name] TEXT NOT NULL
);

CREATE TABLE Cabinet
(
	ID INTEGER PRIMARY KEY IDENTITY,
	CorpsID INT NOT NULL,
	[Name] VARCHAR(5) NOT NULL,
	FOREIGN KEY (CorpsID) REFERENCES Corps (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	UNIQUE (CorpsID, [Name])
);

CREATE TABLE DeviceType
(
	ID INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(30) NOT NULL
);

CREATE TABLE [Group]
(
	ID INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(20) UNIQUE
);

CREATE TABLE IPAddress
(
	ID INT PRIMARY KEY IDENTITY,
	[Address] VARCHAR(39) UNIQUE NOT NULL
);

CREATE TABLE [Status]
(
	ID INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE [User]
(
	ID INT PRIMARY KEY IDENTITY,
	LastName NVARCHAR(30) NOT NULL,
	FirstName NVARCHAR(30) NOT NULL,
	MiddleName NVARCHAR(35) NOT NULL,
	[Login] VARCHAR(30) NOT NULL UNIQUE,
	[Password] VARCHAR(30) NOT NULL,
	GroupID INT NOT NULL,
	FOREIGN KEY (GroupID) REFERENCES [Group] (ID)
);

CREATE TABLE Device
(
	SerialNumber INT NOT NULL PRIMARY KEY,
	InventoryNumber VARCHAR(50) NOT NULL UNIQUE,
	TypeID INT NOT NULL,
	NetworkName VARCHAR(30) NOT NULL,
	FOREIGN KEY (TypeID) REFERENCES DeviceType (ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE DeviceConfiguration
(
	DeviceSerialNumber INT PRIMARY KEY NOT NULL,
	IPAddressID INT,
	DeviceAccountName NVARCHAR(255),
	DeviceAccountPassword VARCHAR(255),
	FOREIGN KEY (DeviceSerialNumber) REFERENCES Device (SerialNumber)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY (IPAddressID) REFERENCES IPAddress (ID)
		ON UPDATE CASCADE
);

CREATE TABLE History
(
	ID INT PRIMARY KEY IDENTITY,
	DeviceSerialNumber INT NOT NULL,
	CorpsID INT NOT NULL,
	CabinetID INT NOT NULL,
	ChangeDate DATE NOT NULL,
	StatusID INT NOT NULL,
	FOREIGN KEY (DeviceSerialNumber) REFERENCES Device (SerialNumber),
	FOREIGN KEY (CorpsID) REFERENCES Corps (ID),
	FOREIGN KEY (CabinetID) REFERENCES Cabinet (ID),
	FOREIGN KEY (StatusID) REFERENCES [Status] (ID)
);

CREATE TABLE SoftwareType
(
	ID INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL
);

CREATE TABLE AvailableSoftware
(
	ID INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(50) UNIQUE,
	TypeID INT
		REFERENCES SoftwareType (ID)
);

CREATE TABLE SoftwareConfiguration
(
	ID INT IDENTITY PRIMARY KEY,
	[Login] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(50) NOT NULL,
	AdditionalNotation NVARCHAR(255)
);

CREATE TABLE DeviceSoftware
(
	DeviceSerialNumber INT NOT NULL
		REFERENCES Device (SerialNumber),
	SoftwareID INT NOT NULL
		REFERENCES AvailableSoftware (ID),
	SoftwareConfigurationID INT
		REFERENCES SoftwareConfiguration (ID),
	PRIMARY KEY (DeviceSerialNumber, SoftwareID)
);
